language: android
jdk: oraclejdk8
sudo: required

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.gradle

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew clean check -Dpre-dex=false

notifications:
  email: false

